const loginComponent = require("./login")
const registerComponent = require("./register")
// const navComponent = require("./nav")
// const journalComponent = require("./entries/journal")
// const listComponent = require("./entries/list")
// const emoteComponent = require("./entries/emote")
// const picker = require("./entries/picker")
// const logoutComponent = require("./logout")

// emoteComponent()
// listComponent()
// journalComponent()
// navComponent()
loginComponent()
registerComponent()
// logoutComponent()