const loginComponent = require("./login")
const registerComponent = require("./register")
const entriesPageComponent = require("./entriesPage")
const homePage = require("./homePage")
const homeNavBtn = require("./homeNavBtn")
const  hideJournalText = require("./settings")
const logoutComponent = require("./logout")

console.log("the fuck")

homeNavBtn()
entriesPageComponent()
hideJournalText()
loginComponent()
registerComponent()
homePage()
logoutComponent()