const loginComponent = require("./login")
const registerComponent = require("./register")
const homePage = require("./homePage")
// const journalComponent = require("./entries/journal")
// const listComponent = require("./entries/list")
// const emoteComponent = require("./entries/emote")
const logoutComponent = require("./logout")
 console.log("k")
loginComponent()
registerComponent()
homePage()
// emoteComponent()
// listComponent()
// journalComponent()

logoutComponent()