const loginComponent = require("./login")
const registerComponent = require("./register")
const homePage = require("./homePage")
const  hideJournalText = require("./settings")
const logoutComponent = require("./logout")
 console.log("k")

hideJournalText()
loginComponent()
registerComponent()
homePage()
logoutComponent()